name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-x64:
    name: Ubuntu ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x64]

    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y libsdl2-dev libogg-dev libvorbis-dev &&
          sudo apt-get install -qq -y bison flex zlib1g-dev

    - name: Run CMake
      run: |
          cd ${{github.workspace}}/SamTSE/Sources
          cmake -B ${{github.workspace}}/SamTSE/Sources/build-x64-tse -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }}
          cd ${{github.workspace}}/SamTFE/Sources
          cmake -B ${{github.workspace}}/SamTFE/Sources/build-x64-tfe -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }} -DTFE=TRUE
          
    - name: Run Build
      run: |
          cd ${{github.workspace}}/SamTSE/Sources/build-x64-tse 
          make ecc
          make -j$(nproc || echo 4) 
          cd ${{github.workspace}}/SamTFE/Sources/build-x64-tfe 
          make ecc
          make -j$(nproc || echo 4)  
          
  build-windows-x64:
    name: Windows ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x64]
    steps:
    - uses: actions/checkout@v3
    
    - uses: microsoft/setup-msbuild@v1.0.2
      with:
        vs-version: '14.0'   

    - name: MS Build SamTFE
      working-directory: SamTFE/Sources
      run: msbuild /m /p:Configuration="${{ matrix.Configuration }}" /p:Platform="${{ matrix.Platform }}" SamTFE.sln
      
    - name: MS Build SamTSE
      working-directory: SamTSE/Sources
      run: msbuild /m /p:Configuration="${{ matrix.Configuration }}" /p:Platform="${{ matrix.Platform }}" SamTSE.sln     
